apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-openlayers
spec:
  replicas: 1
  template:
    metadata:
      name: vue-openlayers
    spec:
      containers:
        - name: vue-openlayers
          image: vue-openlayers:0.0.1 # 실제 배포될 Application 이미지로 수정해줬습니다.
          ports:
            - containerPort: 8080